shared:
    image: node:12

annotations:
    screwdriver.cd/restrictPR: all


jobs:
    first-job:
        requires: [ ~pr, ~commit ]
        steps:
            - echo: echo "this is first job."
    second-job:
        requires: [ first-job ]
        steps:
            - echo: echo "this is second job."
